### ISSUE TITLE
File name too long

### ISSUE THREAD

**Issue by mhingston** [spujadas/elkx-docker#16]
Hi,

Thanks for the docker images. I've followed the [guide](https://github.com/spujadas/elkx-docker#usage-notes) for bootstrapping the container and running it normally. After I set the passwords for `elastic` and `kibana` to `changeme` and stop the container. I then restart it as follows:

`docker-compose up elkx`

**docker-compose.yml**
```yaml
elkx:
  image: sebp/elkx
  ports:
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"
  environment:
    - "TZ=Europe/London"
    - "ELASTICSEARCH_USER=elastic"
    - "ELASTICSEARCH_PASSWORD=changeme"
    - "KIBANA_USER=kibana"
    - "KIBANA_PASSWORD=changeme"
    - "LOGSTASH_USER=elastic"
    - "LOGSTASH_PASSWORD=changeme"
```
I'm getting the following error when the container starts up...

```
elkx_1  | touch: cannot touch '/var/log/elasticsearch/{"error":{"root_cause":[{"type":"security_exception","reason":"failedtoauthenticateuser[elastic]","header":{"WWW-Authenticate":"Basicrealm=\"security\"charset=\"UTF-8\""}}],"type":"security_exception","reason":"failedtoauthenticateuser[elastic]","header":{"WWW-Authenticate":"Basicrealm=\"security\"charset=\"UTF-8\""}},"status":401}.log': File name too long
```
The auth is failing but in addition it looks like elastic is trying to write JSON as a path?

I'm using sebp/elkx:622

**Comment by spujadas** [comment]
Hi there,

> `elkx_1  | touch: cannot touch '/var/log/elasticsearch/{"error":{"root_cause":[{"type":"security_exception","reason":"failedtoauthenticateuser[elastic]","header":{"WWW-Authenticate":"Basicrealm=\"security\"charset=\"UTF-8\""}}],"type":"security_exception","reason":"failedtoauthenticateuser[elastic]","header":{"WWW-Authenticate":"Basicrealm=\"security\"charset=\"UTF-8\""}},"status":401}.log': File name too long`

and

> elastic is trying to write JSON as a path?

are just a consequence of authentication failing. (Nitty-gritty: the base name of the log file, which is the name of the ES cluster, is retrieved by querying ES over HTTP, so if authentication fails, the start-up script will attempt to create a log file named after the JSON-returned error, hence what you're seeing.)

With that out of the way, the problem here seems to be that the bootstrap process failed. Could be for a number of reasons: perhaps because the container where authentication fails isn't the same as the one that the bootstrap process was run on (which is a tricky situation to get out of if not using `docker-compose`).

Anway, here's a baseline process that should work (just tested against `sebp/elkx:622`).

You need two `docker-compose.yml` files: one for bootstrap, one for runtime.

**docker-compose.yml.bootstrap**

	elkx:
	  image: sebp/elkx
	  ports:
	    - "5601:5601"
	    - "9200:9200"
	    - "5044:5044"
	  environment:
	    - ELASTIC_BOOTSTRAP_PASSWORD=changeme

**docker-compose.yml.run** (same as yours, really)

	elkx:
	  image: sebp/elkx
	  ports:
	    - "5601:5601"
	    - "9200:9200"
	    - "5044:5044"
	  environment:
	    - ELASTICSEARCH_USER=elastic
	    - ELASTICSEARCH_PASSWORD=changeme
	    - LOGSTASH_USER=elastic
	    - LOGSTASH_PASSWORD=changeme
	    - KIBANA_USER=kibana
	    - KIBANA_PASSWORD=changeme

Then start a container in bootstrap mode:

	$ docker-compose -f docker-compose.yml.bootstrap up
	Creating elkxdocker_elkx_1
	Attaching to elkxdocker_elkx_1
	elkx_1  | ERROR: Setting [bootstrap.pass] does not exist in the keystore.
	elkx_1  |  * Starting periodic command scheduler cron
	elkx_1  |    ...done.
	elkx_1  |  * Starting Elasticsearch Server
	elkx_1  |    ...done.
	elkx_1  | waiting for Elasticsearch to be up (1/30)
	elkx_1  | waiting for Elasticsearch to be up (2/30)
	elkx_1  | waiting for Elasticsearch to be up (3/30)
	elkx_1  | waiting for Elasticsearch to be up (4/30)
	...

In another shell, `docker exec` into the running container and set up the passwords:

	$ docker exec -it elkxdocker_elkx_1 bash
	root@e30d574bf837:/tmp# /opt/elasticsearch/bin/x-pack/setup-passwords interactive
	Initiating the setup of reserved user elastic,kibana,logstash_system passwords.
	You will be prompted to enter passwords as the process progresses.
	Please confirm that you would like to continue [y/N]y


	Enter password for [elastic]:
	Reenter password for [elastic]:
	Enter password for [kibana]:
	Reenter password for [kibana]:
	Enter password for [logstash_system]:
	Reenter password for [logstash_system]:
	Changed password for user [kibana]
	Changed password for user [logstash_system]
	Changed password for user [elastic]

Stop the running container, and start a container with the runtime `docker-compose.yml` file:

	^CGracefully stopping... (press Ctrl+C again to force)
	Stopping elkxdocker_elkx_1 ...

	$ docker-compose -f docker-compose.yml.run up
	Recreating elkxdocker_elkx_1
	Attaching to elkxdocker_elkx_1
	elkx_1  |  * Starting periodic command scheduler cron
	elkx_1  |    ...done.
	elkx_1  |  * Starting Elasticsearch Server
	elkx_1  |    ...done.
	elkx_1  | waiting for Elasticsearch to be up (1/30)
	elkx_1  | waiting for Elasticsearch to be up (2/30)
	elkx_1  | waiting for Elasticsearch to be up (3/30)
	elkx_1  | waiting for Elasticsearch to be up (4/30)
	elkx_1  | waiting for Elasticsearch to be up (5/30)
	elkx_1  | waiting for Elasticsearch to be up (6/30)
	elkx_1  | waiting for Elasticsearch to be up (7/30)
	elkx_1  | waiting for Elasticsearch to be up (8/30)
	elkx_1  | waiting for Elasticsearch to be up (9/30)
	elkx_1  | Waiting for Elasticsearch cluster to respond (1/30)
	elkx_1  | logstash started.
	elkx_1  |  * Starting Kibana5
	elkx_1  |    ...done.
	elkx_1  | ==> /var/log/elasticsearch/elasticsearch.log <==
	elkx_1  | [2018-03-13T19:35:34,811][INFO ][o.e.n.Node               ] [tHq92_L] starting ...
	...

**Comment by mhingston** [comment]
Thanks @spujadas working now with the 2 `docker-compose.yml` files.

**Comment by shousper** [comment]
Sorry to comment on a closed issue, but the issue isn't old and the proposed solution isn't working for me.

I've split my docker-compose file into 2, but these are still appearing early in the startup:

```
elk_1  | touch: cannot touch '/var/log/elasticsearch/{"error":{"root_cause":[{"type":"security_exception","reason":"failedtoauthenticateuser[elastic]","header":{"WWW-Authenticate":"Basicrealm=\"security\"charset=\"UTF-8\""}}],"type":"security_exception","reason":"failedtoauthenticateuser[elastic]","header":{"WWW-Authenticate":"Basicrealm=\"security\"charset=\"UTF-8\""}},"status":401}.log': File name too long
elk_1  | ==> /var/log/kibana/kibana5.log <==
elk_1  | tail: cannot open '/var/log/elasticsearch/{"error":{"root_cause":[{"type":"security_exception","reason":"failedtoauthenticateuser[elastic]","header":{"WWW-Authenticate":"Basicrealm=\"security\"charset=\"UTF-8\""}}],"type":"security_exception","reason":"failedtoauthenticateuser[elastic]","header":{"WWW-Authenticate":"Basicrealm=\"security\"charset=\"UTF-8\""}},"status":401}.log' for reading: File name too long
```

After startup I jumped into the container and ran the same `curl` command this issue is originating from [here](https://github.com/spujadas/elk-docker/blob/master/start.sh#L125). It gives the same JSON response you can see in the log.

However, if I include the configured username and password as basic auth with `-u "elastic:changeme"` it works perfectly.

Is this perhaps a bug in spujadas/elk-docker, or have I still just failed to configure something? :(

Here are my 2 docker-compose files for reference:

boot.docker-compose.yml
```
elk:
  image: sebp/elkx
  ports:
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"
  volumes:
    - ./.es-data:/var/lib/elasticsearch
  environment:
    - ELASTIC_BOOTSTRAP_PASSWORD=changeme
```

docker-compose.yml
```
elk:
  image: sebp/elkx
  ports:
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"
  volumes:
    - ./.es-data:/var/lib/elasticsearch
  environment:
    - ELASTICSEARCH_USER=elastic
    - ELASTICSEARCH_PASSWORD=changeme
    - LOGSTASH_USER=elastic
    - LOGSTASH_PASSWORD=changeme
    - KIBANA_USER=kibana
    - KIBANA_PASSWORD=changeme
    - LOGSTASH_START=0
```

Thanks in advance!
